Add `url` attribute to FakeRequest class
There are a few methods in `PiwikTracker()` object that accesses the
`request.url` attribute. For example, in `def __get_current_scheme()`:

`if self.request.url.startswith('https:’):`

This will cause tests that initiate the `PiwikTracker` object to fail.

Implement the `url` attribute in FakeRequest, and in the class
constructor, it will get the value of url from `headers['HTTP_REFERER’]`

Example of failure
==================

```
Error in piwikapi.tests.test_tracking.TrackerVerifyTestCase.test_set_visitor_feature_single_plugin
  File "/usr/local/lib/python3.6/site-packages/unittest2/case.py", line 67, in testPartExecutor
    yield
  File "/usr/local/lib/python3.6/site-packages/unittest2/case.py", line 621, in run
    self.setUp()
  File "/Users/hanxue/Github/piwik-python-api/piwikapi/tests/test_tracking.py", line 457, in setUp
    super(TrackerVerifyBaseTestCase, self).setUp()
  File "/Users/hanxue/Github/piwik-python-api/piwikapi/tests/test_tracking.py", line 50, in setUp
    self.pt = PiwikTracker(self.settings['PIWIK_SITE_ID'], self.request)
  File "/Users/hanxue/Github/piwik-python-api/piwikapi/tracking.py", line 75, in __init__
    self.page_url = self.__get_current_url()
  File "/Users/hanxue/Github/piwik-python-api/piwikapi/tracking.py", line 367, in __get_current_url
    url = self.__get_current_scheme() + '://'
  File "/Users/hanxue/Github/piwik-python-api/piwikapi/tracking.py", line 337, in __get_current_scheme
    if self.request.url.startswith('https:'):
AttributeError: 'FakeRequest' object has no attribute 'url'
```